### ISSUE TITLE
Export of incomplete entities

### ISSUE THREAD

**Issue by baszoetekouw** [janus-ssp/janus#445]
When exporting an entity with incomplete metadata, Janus complains that the metadata is incomplete.  This is rather annoying;  it's fine if Janus _warns_ that the metadata is incomplete, but it should the operator's decision to export the data.
Please remove this restriction.

![screen shot 2014-04-08 at 16 59 30](https://cloud.githubusercontent.com/assets/1461740/2645078/b1847482-bf2e-11e3-96d3-345fb234d5c2.png)

**Comment by thijskh** [comment]
The REST API allows this export. For the UI, see #566
