### ISSUE TITLE
Visually indicate when a connection in disabled in Janus screens

### ISSUE THREAD

**Issue by pmeulen** [janus-ssp/janus#464]
When a connection is disabled this should be visible in the lists where a connection appears. And when the connection is being edited:
- Dashboard - connection: Show disabled connection in the list of IdP and SP connections. E.g. by showing these in a lighter color
- Edit connection: When the connection is disabled, indicate this. E.g. "Edit connection - <connection ID> (Revision N) (Disabled)"
- Edit connection - ACL and consent tabs: Visually indicate connections that are disabled

**Comment by thijskh** [comment]
These are all done.
