### ISSUE TITLE
Can't reuse enityid that has been used in old revisions

### ISSUE THREAD

**Issue by baszoetekouw** [janus-ssp/janus#474]
In the new SR, I wanted to do the following:

change the entityid of an existing IdP
create a new SP with the old entityid of the IdP
However, this resulted in the error:
"Error
Connection ID has already been used in a previous revision of an existing connection"

That's pretty annoying, and will give a lot more clashes in the future. It is really necessary for entityids to be unique over all revisions, rather than just for the latest revisions?

**Comment by relaxnow** [comment]
Now that Lucas has migrated away from entityid to eid there should be no need. I've removed the check.
