### ISSUE TITLE
Create export of all metadata

### ISSUE THREAD

**Issue by lucasvanlierop** [janus-ssp/janus#499]
Create and exporter which
- [ ] exports a file containing all connections and their metadata
- [ ] invoke a hook which can be notified when the file has been changed

Update gui
- [ ] Add a button to the gui which can trigger the export
- [ ] Show the return value of the hook script

**Comment by thijskh** [comment]
The REST API currently performs this function adequately. If we need a GUI function it should be just calling the API functions internally. I'm closing this issue.
