### ISSUE TITLE
Set ARP on JSON import of metadata

### ISSUE THREAD

**Issue by maartenk** [janus-ssp/janus#503]
When importing JSON metadata, based on the JSON export of another entity, the ARP information is not set. As i understand the ARP data is now stored at the SP enity, so it would be nice if the ARP data is also set based on the JSON import information.

For instance: JSON export contains the below
```
  "attributes": [
    "urn:mace:dir:attribute-def:uid"
  ],
```
After import: ARP is set to UID (and not the default ARP).

**Comment by thijskh** [comment]
This works when using the REST API. Eventually the GUI functions should use the REST API functions thereby solving this issue: #566
