### ISSUE TITLE
Cannot import edugain metadata - too large

### ISSUE THREAD

**Issue by thijskh** [janus-ssp/janus#506]
When using import on the edugain metadata (http://mds.edugain.org), janus fails.

`Caused by: SimpleSAML_Error_Exception: Nothing to import`

This appears to be caused by it being to large to insert into memcache:

`PHP Notice:  MemcachePool::set(): Server localhost (tcp 11211, udp 0) failed with: SERVER_ERROR object too large for cache\r\n (3) in /opt/www/serviceregistry-4.0.6/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Memcache.php on line 135`

Enlarging the objects memcache accepts is advised against because it would impact overall performance. Can we find a way to deal with metadata of this size?

**Comment by relaxnow** [comment]
Fixed with SURFconext/SURFconext-deploy@b2041ad
