### ISSUE TITLE
Migrate invalid unspecified NameID

### ISSUE THREAD

**Issue by relaxnow** [janus-ssp/janus#554]
In the past the invalid 'unspecified' NameID was used and it should be migrated.
From: 'urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified';
To: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified';

**Comment by relaxnow** [comment]
Requires manual migration

**Comment by thijskh** [comment]
We are now migrating our own apps. Then we'll approach the affected external SP's.

**Comment by thijskh** [comment]
Everything has been migrated away. This value can be removed from Janus. A migration is not needed because this has already been completed and it's a SURFconext-specific error.

**Comment by thijskh** [comment]
For Janus this is config-only. The configuration has been updated in the deploy repository. This issue can therefore be closed.
