### ISSUE TITLE
IdP with many revisions / SP connections disappears from EB

### ISSUE THREAD

**Issue by thijskh** [janus-ssp/janus#588]
We have seen the issue that after an EB cache flush, a single IdP is suddenly unknown to EB. All other IdP's continue to work fine.

The problem went away after disconnecting a number of SP's. When reconnecting several of those, the problem reappeared and disappeared again after again reducing the number of connected IdP's. What sets this IdP apart in our configuration is that it has by far the most revisions (>260 at time of writing) and also many SP's connected (around 100). However, there are IdP's with more SP's connected.

A working theory is that the number of revisions and/or sp's aggravates Janus' performance issues to a level where some kind of timeout or memory limit is reached. No relevant logging information has been found to confirm this, as yet.

Janus version 1.20.5, Engineblock version 4.3.8.

**Comment by relaxnow** [comment]
> A working theory is that the number of revisions and/or sp's aggravates Janus' performance issues to a level where some kind of timeout or memory limit is reached. No relevant logging information has been found to confirm this, as yet.

This seems unlikely to me, a timeout or memory issue in PHP would kill the process and would not send any data at all. Though I must admit to have no better theory at the moment :smile:

**Comment by relaxnow** [comment]
I looked into this bug but cannot find any way to reproduce this or what exactly triggered the disappearance. In light of major changes in metadata handling I would suggest closing this for now until maybe it rears it's ugly head again.
