### ISSUE TITLE
Wrong documentation URL

### ISSUE THREAD

**Issue by tvdijen** [janus-ssp/janus#607]
On a connection, on the Manipulation-tab, there is a broken link to documentation on Attribute Manipulation:

https://wiki.surfnet.nl/display/conextdocumentation/Attribute+manipulations
Does anyone have any idea where this was moved to?

**Comment by thijskh** [comment]
This page is still there but inaccessible externally (it's part of the wiki space for SURFconext administrators).

The content (and more) is available at https://github.com/OpenConext/OpenConext-engineblock/wiki/Attribute-Manipulations, I'll fix that.
