### ISSUE TITLE
Importing Metadata via API

### ISSUE THREAD

**Issue by precurse** [janus-ssp/janus#622]
We're interested in using the API similarly to the way the Janus GUI is used.  We'd like to be able to send an API request to create a new entry based on a metadata URL.

However, when we use the API with only the metadata URL specified, it creates an entity with only the metadata URL string -- no parsing of the metadata file happens like it does from the web GUI.

It'd be a real nice way of bootstrapping a brand new federation without having to install mujina-idp beforehand.  Not sure how easy/difficult it would be. If you could even point us to where to start looking into it, I'm sure we can add the functionality on our own.

Thanks!

**Comment by pmeulen** [comment]
Hi Klaus,

As far as I know importing from an external metadata URL directly is not available through the API, and if it were, it would only get you so far because things like ARP and ACL cannot be set from SAML metadata in Janus. However using the Janus API you can configure the new entry (connection) you just created. For an example see: https://github.com/janus-ssp/client/blob/master/examples/connection-crud.php#L86

> On 25 Feb 2017, at 20:38, Andrew Klaus <notifications@github.com> wrote:
> 
> We're interested in using the API similarly to the way the Janus GUI is used. We'd like to be able to send an API request to create a new entry based on a metadata URL.
> 
> However, when we use the API with only the metadata URL specified, it creates an entity with only the metadata URL string -- no parsing of the metadata file happens like it does from the web GUI.
> 
> It'd be a real nice way of bootstrapping a brand new federation without having to install mujina-idp beforehand. Not sure how easy/difficult it would be. If you could even point us to where to start looking into it, I'm sure we can add the functionality on our own.
> 
> Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Pieter.

**Comment by precurse** [comment]
Thanks for the detailed explanation! We might just need to wind up parsing the metadata then passing it to the API. I'll close the ticket.
